#include "../interface/ObjectIDHandler.h"

OBJECT_ID_INFO_COLLECTION*  OBJECT_ID_INFO_COLLECTION::SINGLETON_OBJECT_ID_INFO = new OBJECT_ID_INFO_COLLECTION();

OBJECT_ID_INFO_COLLECTION::OBJECT_ID_INFO_COLLECTION(){
    
}
